/* eslint @typescript-eslint/no-var-requires: "off" */
export const WhiteLogo = require("./images/WhiteLogo.png");
export const WhiteLogoVector = require("./images/WhiteLogoVector.png");
export const Logo = require("./images/Logo.png");
export const GeotaggerPattern = require("./images/GeotaggerPattern.png");
export const ImagePlaceholder = require("./images/ImagePlaceholder.png");
export const StockImage = require("./images/Bled.jpg");
export const MapImage = require("./images/GoogleMap.png");
export const WorldMap = require("./images/WorldMap.png");
